runtime: python27
api_version: 1
threadsafe: true
  
handlers:
- url: /.*
  script: voyagewithus_api.application
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: PIL
  version: latest
